module.exports = {
  purge: [
    "./index.html",
    "./app/js/view/**/*.jsx",
  ],
  future: {
    removeDeprecatedGapUtilities: true,
  },
  theme: {
    screens: {
      sm: "520px",
      md: "768px",
      lg: "1280px",
    },
    colors: {
      transparent: "transparent",
      current: "currentColor",

      black: "#1d1d1d",
      white: "#fafafa",

      gray: {
        light: "#a0aec0",
        default: "#718096",
        // dark: "#2d3748",
      },
    },
    spacing: {
      0: "0",
      1: "0.25rem",
      2: "0.5rem",
      3: "0.75rem",
      4: "1rem",
      8: "2rem",
      16: "4rem",
    },
    extend: {},
  },
  variants: {
    accessibility: ["responsive", "focus"],
    alignContent: ["responsive"],
    alignItems: ["responsive"],
    alignSelf: ["responsive"],
    appearance: ["responsive"],
    backgroundAttachment: false,
    backgroundColor: ["hover", "focus"],
    backgroundOpacity: ["hover", "focus"],
    backgroundPosition: false,
    backgroundRepeat: false,
    backgroundSize: false,
    borderCollapse: false,
    borderColor: ["hover", "focus"],
    borderOpacity: ["hover", "focus"],
    borderRadius: ["responsive"],
    borderStyle: ["responsive"],
    borderWidth: ["responsive"],
    boxShadow: ["hover", "focus"],
    boxSizing: false,
    container: ["responsive"],
    cursor: false,
    display: ["responsive"],
    divideColor: false,
    divideOpacity: false,
    divideWidth: false,
    fill: false,
    flex: ["responsive"],
    flexDirection: ["responsive"],
    flexGrow: ["responsive"],
    flexShrink: ["responsive"],
    flexWrap: ["responsive"],
    float: false,
    clear: false,
    fontFamily: false,
    fontSize: ["responsive"],
    fontSmoothing: false,
    fontStyle: false,
    fontWeight: ["hover", "focus"],
    height: ["responsive"],
    justifyContent: ["responsive"],
    inset: false,
    letterSpacing: ["responsive"],
    lineHeight: ["responsive"],
    listStylePosition: false,
    listStyleType: false,
    margin: ["responsive"],
    maxHeight: ["responsive"],
    maxWidth: ["responsive"],
    minHeight: ["responsive"],
    minWidth: ["responsive"],
    objectFit: false,
    objectPosition: false,
    opacity: ["hover", "focus"],
    order: false,
    outline: ["focus"],
    overflow: false,
    overscrollBehavior: false,
    padding: ["responsive"],
    placeholderColor: ["focus"],
    placeholderOpacity: ["focus"],
    pointerEvents: false,
    position: ["responsive"],
    resize: false,
    space: ["responsive"],
    stroke: false,
    strokeWidth: false,
    tableLayout: false,
    textAlign: false,
    textColor: ["hover", "focus"],
    textOpacity: ["hover", "focus"],
    textDecoration: ["hover", "focus"],
    textTransform: false,
    userSelect: false,
    verticalAlign: false,
    visibility: ["responsive"],
    whitespace: false,
    width: ["responsive"],
    wordBreak: false,
    zIndex: ["responsive"],
    gap: false,
    gridAutoFlow: false,
    gridTemplateColumns: false,
    gridColumn: false,
    gridColumnStart: false,
    gridColumnEnd: false,
    gridTemplateRows: false,
    gridRow: false,
    gridRowStart: false,
    gridRowEnd: false,
    transform: false,
    transformOrigin: false,
    scale: false,
    rotate: false,
    translate: false,
    skew: false,
    transitionProperty: false,
    transitionTimingFunction: false,
    transitionDuration: false,
    transitionDelay: false,
    animation: false,
  },
  corePlugins: {
    preflight: false,
    clear: false,
    float: false,
    fontSmoothing: false,
  },
  plugins: [],
};
